#!/usr/bin/env bash
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

else
    path_file=$1
    ip=$2
    username=$3
    path_sshKey=$4

    scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~/
fi
