#!/bin/env bash
# Update the package list

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
# Configure Nginx to listen on port 80
sudo sed -i 's/.*listen \(.*\)/listen 80;/g' /etc/nginx/sites-available/default
echo 'Hello World!' > /var/www/html/index.html
# Restart Nginx (you can't use systemctl, so use service)
sudo service nginx start

